### ISSUE TITLE
Replace lodash dependencies

### ISSUE THREAD

**Issue by phated** [gulpjs/fined#7]

**Comment by sttk** [comment]
@phated Can I send a PR about this issue?

**Comment by jonschlinkert** [comment]
@sttk fwiw I have a pr for this already ready to send. I'll try to push it up this weekend if I get a chance

**Comment by phated** [comment]
I'll take any PR that is sent.

**Comment by jonschlinkert** [comment]
Ok I'll let @sttk do it.

**Comment by sttk** [comment]
@jonschlinkert  Oh, OK. I ask you to send the PR.

**Comment by sttk** [comment]
@jonschlinkert Oh sorry, I might misunderstand...

> Ok I'll let @sttk do it.

Do I send a PR?

**Comment by phated** [comment]
@sttk yes, please send a PR

**Comment by sttk** [comment]
I've sended the PR #8
